--- 
title: "Better Data and Better Results"
author: "Abdulla Alhammadi | عبدالله الحمادي"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---
# Introduction {#intro}

## The Purpose

This project is a personal initiative of how setting better standards can help utilize modern technology to better collect and analyze data for specific applications, as well as how to make the most out of public data. In this case, the task will be to look into developing the standards for collecting public data, and how to make the most with what is available currently have to create better insights. In this case, for public policy.

## Abstract

With the advancements in data technologies, the prevalence of data has skyrocketed in recent years. Due to this, the availability of data has increased significantly. 

> "There are 2.5 quintillion bytes of data created every day— 
> which is why you need IBM Cloud Object Storage"
>
> --- an IBM Advertisement.

That is indeed an impressively large amount of data, but the IBM Cloud Object Storage is not actually needed because it is very likely that most of the data is probably random back-end logs or cat videos. In any case, most of the data available may not be useful, usable data. This document will go through the importance of developing standards and criteria for the processes of gathering, entering, and handling of data for the purpose of developing high quality datasets to provide valuable and beneficial results.
